# Generated by Django 5.1.1 on 2024-10-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_book1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book1',
        ),
    ]
