# Generated by Django 5.1.1 on 2024-10-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_book1'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
