# Generated by Django 5.1.1 on 2024-10-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('product_stock_quantity', models.IntegerField(max_length=100)),
                ('product_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
