# Generated by Django 5.1.1 on 2024-10-16 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_customer1model'),
    ]

    operations = [
        migrations.CreateModel(
            name='userproduct',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='productuser',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('user_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userproduct')),
            ],
        ),
    ]
